<a href="https://colab.research.google.com/github/Ramnarayan-Choudhary/new-ML-data-/blob/main/IE506_21b030030_assignment1_q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
drug_vs_Body_measurements=pd.read_csv('/content/file1.csv')
drug_vs_Body_measurements

,attr1,attr2,attr3,attr4,attr5,attr6,attr7,atr8,attr9,attr10,attr11,attr12,attr13,attr14,attr15,attr16,attr17,attr18
0,42.9,26.0,31.5,13.1,10.4,18.8,14.1,106.2,71.5,32.5,26.0,34.5,36.5,23.5,16.5,21,1,65.6
1,43.7,28.5,33.5,14.0,11.8,20.6,15.1,110.5,79.0,34.4,28.0,36.5,37.5,24.5,17.0,23,1,71.8
2,40.1,28.2,33.3,13.9,10.9,19.7,14.1,115.1,83.2,33.4,28.8,37.0,37.3,21.9,16.9,28,1,80.7
3,44.3,29.9,34.0,13.9,11.2,20.9,15.0,104.5,77.8,31.0,26.2,37.0,34.8,23.0,16.6,23,1,72.6
4,41.0,26.8,32.2,14.9,10.6,17.8,14.0,107.5,78.0,36.0,29.0,34.5,35.0,22.0,16.5,23,1,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,38.5,25.6,31.7,11.8,10.2,16.8,12.9,92.8,74.7,28.1,23.1,34.4,32.7,20.9,15.2,19,0,60.0
442,35.3,25.4,28.5,10.6,10.4,17.0,12.6,95.9,60.8,26.8,22.8,34.4,33.1,21.0,15.4,31,0,46.8
443,36.2,28.7,27.8,12.4,10.2,17.9,13.2,96.1,66.9,26.2,22.6,35.0,35.2,22.4,15.2,34,0,57.3
444,34.9,28.7,32.9,13.4,10.8,17.9,12.9,98.5,68.8,29.6,25.1,34.4,35.0,21.0,15.9,34,0,64.1
445,38.7,29.7,32.0,12.8,10.5,18.4,13.8,103.8,63.7,26.4,23.0,36.5,34.1,21.3,15.0,24,0,63.6

In [ ]:

drug_vs_Body_measurements_data_description_file = pd.read_csv("/content/desc1.txt (1).txt", delimiter=';')

drug_vs_Body_measurements_data_description_file.head()

  Body measurements of 446 physically active individuals.
0                                        Description
1  Body girth measurements and skeletal diameter ...
2                                             Format
3  A data frame with 446 observations on the foll...
4                                              attr1

Perform standardization of each column in the data frame and create a new data
frame.

In [ ]:
drug_vs_Body_measurements.columns=[ 'biacromial diameter','biiliac diameter', 'bitrochanteric diameter','elbow diameter' ,'wrist diameter' ,'knee diameter','ankle diameter','shoulder girth','waist girth', 'bicep girth','forearm girth' ,'knee girth','calf maximum girth','ankle minimum girth','wrist minimum girth','age','male','weights'     ]

In [ ]:
import scipy
from scipy import stats

In [ ]:
std_drug_vs_Body_measurements=stats.zscore(drug_vs_Body_measurements)
std_drug_vs_Body_measurements

,attr1,attr2,attr3,attr4,attr5,attr6,attr7,atr8,attr9,attr10,attr11,attr12,attr13,attr14,attr15,attr16,attr17,attr18
0,1.336951,-0.805603,-0.222423,-0.186284,-0.140704,0.020248,0.214666,-0.189357,-0.498005,0.343516,0.035930,-0.631905,0.161063,0.723097,0.286831,-0.969623,1.0,-0.253068
1,1.599355,0.331275,0.777582,0.476611,1.321123,1.352655,1.011182,0.220563,0.170143,0.791149,0.741871,0.128769,0.507084,1.251442,0.643968,-0.762013,1.0,0.207589
2,0.418537,0.194850,0.677582,0.402956,0.381377,0.686452,0.214666,0.659082,0.544306,0.555553,1.024247,0.318937,0.437880,-0.122254,0.572540,-0.242988,1.0,0.868856
3,1.796158,0.967926,1.027583,0.402956,0.694625,1.574723,0.931530,-0.351418,0.063239,-0.009878,0.106524,0.318937,-0.427173,0.458925,0.358258,-0.762013,1.0,0.267029
4,0.713742,-0.441802,0.127579,1.139505,0.068128,-0.719977,0.135015,-0.065427,0.081057,1.168103,1.094841,-0.631905,-0.357969,-0.069419,0.286831,-0.762013,1.0,0.148149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,-0.106271,-0.987503,-0.122422,-1.143799,-0.349537,-1.460203,-0.741152,-1.466781,-0.212929,-0.693107,-0.987684,-0.669938,-1.153818,-0.650598,-0.641725,-1.177234,-1.0,-0.669146
442,-1.155886,-1.078453,-1.722430,-2.027659,-0.140704,-1.312158,-0.980107,-1.171258,-1.451230,-0.999382,-1.093575,-0.669938,-1.015409,-0.597764,-0.498871,0.068428,-1.0,-1.649901
443,-0.860682,0.422225,-2.072431,-0.701869,-0.349537,-0.645955,-0.502198,-1.152192,-0.907803,-1.140740,-1.164169,-0.441736,-0.288765,0.141918,-0.641725,0.379843,-1.0,-0.869755
444,-1.287088,0.422225,0.477581,0.034681,0.276960,-0.645955,-0.741152,-0.923399,-0.738539,-0.339713,-0.281743,-0.669938,-0.357969,-0.597764,-0.141734,0.379843,-1.0,-0.364518
445,-0.040670,0.876976,0.027579,-0.407249,-0.036288,-0.275842,-0.024288,-0.418149,-1.192880,-1.093621,-1.022981,0.128769,-0.669388,-0.439260,-0.784580,-0.658208,-1.0,-0.401668

In [ ]:
print('max:',std_drug_vs_Body_measurements.max())
print('maximum done **********')
print('min:',std_drug_vs_Body_measurements.min())
print('min done **********')
print('median:',std_drug_vs_Body_measurements.median())
print('median done **********')
print('first quartile:',std_drug_vs_Body_measurements.quantile(q=0.25, axis=0, numeric_only=True, interpolation='linear'))
print('first quartile done **********')
print('third quartile:',std_drug_vs_Body_measurements.quantile(q=0.75, axis=0, numeric_only=True, interpolation='linear'))
print('third qurtile done **********')

max: attr1     2.419367
attr2     3.150732
attr3     2.927592
attr4     2.465295
attr5     2.887366
attr6     4.091490
attr7     2.683865
atr8      2.537087
attr9     3.216900
attr10    2.652360
attr11    2.330237
attr12    4.882977
attr13    4.036500
attr14    3.787494
attr15    2.501080
attr16    3.597801
attr17    1.000000
attr18    3.521351
dtype: float64
maximum done **********
min: attr1    -2.041500
attr2    -4.125286
attr3    -2.822435
attr4    -2.543244
attr5    -2.542277
attr6    -2.274452
attr7    -3.130699
atr8     -2.124560
attr9    -1.709581
attr10   -2.036006
attr11   -2.223080
attr12   -2.723756
attr13   -2.641709
attr14   -3.028147
attr15   -2.213128
attr16   -1.281039
attr17   -1.000000
attr18   -2.006539
dtype: float64
min done **********
median: attr1    -0.040670
attr2     0.035687
attr3     0.027579
attr4    -0.112629
attr5    -0.036288
attr6    -0.053774
attr7    -0.024288
atr8      0.010837
attr9    -0.137205
attr10   -0.045218
attr11   -0.034664
attr12   -0.061400
attr13   -0.046550
attr14   -0.069419
attr15    0.001121
attr16   -0.242988
attr17    0.000000
attr18   -0.078464
dtype: float64
median done **********
first quartile: attr1    -0.860682
attr2    -0.578227
attr3    -0.672425
attr4    -0.701869
attr5    -0.767202
attr6    -0.645955
attr7    -0.741152
atr8     -0.844752
attr9    -0.809808
attr10   -0.858025
attr11   -0.881793
attr12   -0.669938
attr13   -0.703990
attr14   -0.637389
attr15   -0.784580
attr16   -0.762013
attr17   -1.000000
attr18   -0.793598
Name: 0.25, dtype: float64
first quartile done **********
third quartile: attr1     0.771143
attr2     0.649601
attr3     0.677582
attr4     0.771230
attr5     0.694625
attr6     0.612429
attr7     0.772227
atr8      0.809227
attr9     0.673482
attr10    0.791149
attr11    0.874235
attr12    0.613698
attr13    0.645492
attr14    0.604220
attr15    0.715395
attr16    0.587453
attr17    1.000000
attr18    0.723971
Name: 0.75, dtype: float64
third qurtile done **********

Split the data into two sets such that 80% of the data is considered as set T1 and 20% of the
data is considered as set T2.

In [ ]:
T1=drug_vs_Body_measurements.iloc[:357,:]
print(T1)

     attr1  attr2  attr3  attr4  attr5  attr6  attr7   atr8  attr9  attr10  \
0     42.9   26.0   31.5   13.1   10.4   18.8   14.1  106.2   71.5    32.5
1     43.7   28.5   33.5   14.0   11.8   20.6   15.1  110.5   79.0    34.4
2     40.1   28.2   33.3   13.9   10.9   19.7   14.1  115.1   83.2    33.4
3     44.3   29.9   34.0   13.9   11.2   20.9   15.0  104.5   77.8    31.0
4     41.0   26.8   32.2   14.9   10.6   17.8   14.0  107.5   78.0    36.0
..     ...    ...    ...    ...    ...    ...    ...    ...    ...     ...
352   36.0   25.2   28.4   11.2    9.9   16.8   12.1  102.5   72.4    27.6
353   35.9   25.1   28.2   11.6    8.5   16.8   11.0   98.4   71.0    28.4
354   35.0   27.1   30.1   12.4    9.9   18.2   12.5   96.8   69.1    28.9
355   35.2   24.4   29.8   13.0    9.2   17.3   12.2  103.9   66.1    27.8
356   34.9   26.2   28.5   10.4    8.7   16.0   11.1   92.7   59.5    23.2

     attr11  attr12  attr13  attr14  attr15  attr16  attr17  attr18
0      26.0    34.5    36.5    23.5    16.5      21       1    65.6
1      28.0    36.5    37.5    24.5    17.0      23       1    71.8
2      28.8    37.0    37.3    21.9    16.9      28       1    80.7
3      26.2    37.0    34.8    23.0    16.6      23       1    72.6
4      29.0    34.5    35.0    22.0    16.5      23       1    71.0
..      ...     ...     ...     ...     ...     ...     ...     ...
352    23.8    33.2    34.4    21.3    14.6      20       0    54.4
353    23.6    34.2    34.0    19.8    13.8      20       0    58.0
354    23.1    35.0    34.4    20.0    15.0      20       0    59.8
355    24.0    35.3    33.7    22.0    14.6      23       0    54.8
356    20.8    31.6    29.6    18.6    13.8      20       0    43.2

[357 rows x 18 columns]

In [ ]:
T2=drug_vs_Body_measurements.iloc[357:,:]
print(T2)

     attr1  attr2  attr3  attr4  attr5  attr6  attr7   atr8  attr9  attr10  \
357   36.0   28.1   31.0   11.5    9.7   17.5   12.8  105.0   71.5    26.8
358   36.4   27.7   29.8   11.2    9.0   16.9   12.2   94.0   65.0    25.0
359   35.5   27.7   30.7   11.6    8.9   17.9   11.5  101.5   71.5    28.4
360   34.1   18.7   27.2   11.2    9.5   16.1   11.9   92.0   63.0    24.1
361   37.1   25.0   29.3   13.0   10.9   17.5   13.0  108.5   70.0    30.1
..     ...    ...    ...    ...    ...    ...    ...    ...    ...     ...
441   38.5   25.6   31.7   11.8   10.2   16.8   12.9   92.8   74.7    28.1
442   35.3   25.4   28.5   10.6   10.4   17.0   12.6   95.9   60.8    26.8
443   36.2   28.7   27.8   12.4   10.2   17.9   13.2   96.1   66.9    26.2
444   34.9   28.7   32.9   13.4   10.8   17.9   12.9   98.5   68.8    29.6
445   38.7   29.7   32.0   12.8   10.5   18.4   13.8  103.8   63.7    26.4

     attr11  attr12  attr13  attr14  attr15  attr16  attr17  attr18
357    22.0    33.8    33.5    21.1    15.3      28       0    60.5
358    22.2    31.6    31.6    18.8    14.2      23       0    46.4
359    23.5    39.1    38.2    20.4    14.4      19       0    64.4
360    22.0    30.0    31.2    20.4    14.4      28       0    48.8
361    25.2    35.8    35.0    21.7    16.0      19       0    62.2
..      ...     ...     ...     ...     ...     ...     ...     ...
441    23.1    34.4    32.7    20.9    15.2      19       0    60.0
442    22.8    34.4    33.1    21.0    15.4      31       0    46.8
443    22.6    35.0    35.2    22.4    15.2      34       0    57.3
444    25.1    34.4    35.0    21.0    15.9      34       0    64.1
445    23.0    36.5    34.1    21.3    15.0      24       0    63.6

[89 rows x 18 columns]

 To perform ℓ2 regularized least squares regression, choose regularization constant
λ ∈ {10−5
, 10−4
, 10−3
, 10−2
, 10−1
, 1, 10, 100, 1000, 10000} using a 5-fold cross-validation on the
full train set T1. Use average R2
scores of the folds as the criterion to choose best regularization
parameter λ
⋆
. Perform ℓ2 regularized least squares regression with best regularization parameter λ
⋆ obtained from the cross-validation procedure on the set T1 and obtain the regression
coefficients. From the regression coefficients obtained, indicate the relative importance of each
attribute in predicting the response variable using the magnitude and sign of the regression coefficients. Compare the regression coefficients with those obtained in Question 1, discuss your
observations.

In [ ]:
cols = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
response_cols=[17]
X_data = T1[T1.columns[cols]]
print(X_data)
print('*****************************')
Y_data=T1[T1.columns[response_cols]]

     attr2  attr3  attr4  attr5  attr6  attr7   atr8  attr9  attr10  attr11  \
0     26.0   31.5   13.1   10.4   18.8   14.1  106.2   71.5    32.5    26.0
1     28.5   33.5   14.0   11.8   20.6   15.1  110.5   79.0    34.4    28.0
2     28.2   33.3   13.9   10.9   19.7   14.1  115.1   83.2    33.4    28.8
3     29.9   34.0   13.9   11.2   20.9   15.0  104.5   77.8    31.0    26.2
4     26.8   32.2   14.9   10.6   17.8   14.0  107.5   78.0    36.0    29.0
..     ...    ...    ...    ...    ...    ...    ...    ...     ...     ...
352   25.2   28.4   11.2    9.9   16.8   12.1  102.5   72.4    27.6    23.8
353   25.1   28.2   11.6    8.5   16.8   11.0   98.4   71.0    28.4    23.6
354   27.1   30.1   12.4    9.9   18.2   12.5   96.8   69.1    28.9    23.1
355   24.4   29.8   13.0    9.2   17.3   12.2  103.9   66.1    27.8    24.0
356   26.2   28.5   10.4    8.7   16.0   11.1   92.7   59.5    23.2    20.8

     attr12  attr13  attr14  attr15  attr16  attr17
0      34.5    36.5    23.5    16.5      21       1
1      36.5    37.5    24.5    17.0      23       1
2      37.0    37.3    21.9    16.9      28       1
3      37.0    34.8    23.0    16.6      23       1
4      34.5    35.0    22.0    16.5      23       1
..      ...     ...     ...     ...     ...     ...
352    33.2    34.4    21.3    14.6      20       0
353    34.2    34.0    19.8    13.8      20       0
354    35.0    34.4    20.0    15.0      20       0
355    35.3    33.7    22.0    14.6      23       0
356    31.6    29.6    18.6    13.8      20       0

[357 rows x 16 columns]
*****************************

In [ ]:
X_array = T1[T1.columns[cols]].to_numpy()
X_array

array([[26. , 31.5, 13.1, ..., 16.5, 21. ,  1. ],
       [28.5, 33.5, 14. , ..., 17. , 23. ,  1. ],
       [28.2, 33.3, 13.9, ..., 16.9, 28. ,  1. ],
       ...,
       [27.1, 30.1, 12.4, ..., 15. , 20. ,  0. ],
       [24.4, 29.8, 13. , ..., 14.6, 23. ,  0. ],
       [26.2, 28.5, 10.4, ..., 13.8, 20. ,  0. ]])

In [ ]:
X = np.hstack((X_array, np.ones((X_array.shape[0], 1), dtype=X_array.dtype)))

X

array([[26. , 31.5, 13.1, ..., 21. ,  1. ,  1. ],
       [28.5, 33.5, 14. , ..., 23. ,  1. ,  1. ],
       [28.2, 33.3, 13.9, ..., 28. ,  1. ,  1. ],
       ...,
       [27.1, 30.1, 12.4, ..., 20. ,  0. ,  1. ],
       [24.4, 29.8, 13. , ..., 23. ,  0. ,  1. ],
       [26.2, 28.5, 10.4, ..., 20. ,  0. ,  1. ]])

In [ ]:
y_data = T1[T1.columns[response_cols]]

In [ ]:

y = T1[T1.columns[response_cols]].to_numpy()
y

array([[ 65.6],
       [ 71.8],
       [ 80.7],
       [ 72.6],
       [ 71. ],
       [ 79.6],
       [ 93.8],
       [ 70. ],
       [ 72.4],
       [ 85.9],
       [ 78.8],
       [ 77.8],
       [ 66.2],
       [ 86.4],
       [ 81.8],
       [ 89.6],
       [ 82.8],
       [ 76.4],
       [ 63.2],
       [ 60.9],
       [ 74.8],
       [ 70. ],
       [ 72.4],
       [ 84.1],
       [ 69.1],
       [ 59.5],
       [ 67.2],
       [ 61.3],
       [ 68.6],
       [ 80.1],
       [ 75.6],
       [ 86.2],
       [ 75.3],
       [ 87.1],
       [ 55.2],
       [ 57. ],
       [ 61.4],
       [ 76.8],
       [ 86.8],
       [ 72.2],
       [ 71.6],
       [ 84.8],
       [ 68.2],
       [ 66.1],
       [ 72. ],
       [ 64.6],
       [ 74.8],
       [ 70. ],
       [101.6],
       [ 63.2],
       [ 79.1],
       [ 78.9],
       [ 67.7],
       [ 66. ],
       [ 68.2],
       [ 63.9],
       [ 72. ],
       [ 56.8],
       [ 74.5],
       [ 90.9],
       [ 93. ],
       [ 80.9],
       [ 72.7],
       [ 68. ],
       [ 70.9],
       [ 72.5],
       [ 72.5],
       [ 83.4],
       [ 75.5],
       [ 73. ],
       [ 70.2],
       [ 73.4],
       [ 70.5],
       [ 68.9],
       [102.3],
       [ 68.4],
       [ 65.9],
       [ 75.7],
       [ 84.5],
       [ 87.7],
       [ 86.4],
       [ 73.2],
       [ 53.9],
       [ 72. ],
       [ 55.5],
       [ 58.4],
       [ 83.2],
       [ 72.7],
       [ 64.1],
       [ 72.3],
       [ 65. ],
       [ 86.4],
       [ 65. ],
       [ 88.6],
       [ 84.1],
       [ 66.8],
       [ 75.5],
       [ 93.2],
       [ 82.7],
       [ 58. ],
       [ 79.5],
       [ 78.6],
       [ 71.8],
       [116.4],
       [ 72.2],
       [ 83.6],
       [ 85.5],
       [ 90.9],
       [ 85.9],
       [ 89.1],
       [ 75. ],
       [ 77.7],
       [ 86.4],
       [ 90.9],
       [ 73.6],
       [ 76.4],
       [ 69.1],
       [ 84.5],
       [ 64.5],
       [ 69.1],
       [108.6],
       [ 86.4],
       [ 80.9],
       [ 87.7],
       [ 94.5],
       [ 80.2],
       [ 72. ],
       [ 71.4],
       [ 72.7],
       [ 84.1],
       [ 76.8],
       [ 63.6],
       [ 80.9],
       [ 80.9],
       [ 85.5],
       [ 68.6],
       [ 67.7],
       [ 66.4],
       [102.3],
       [ 70.5],
       [ 95.9],
       [ 84.1],
       [ 87.3],
       [ 71.8],
       [ 65.9],
       [ 95.9],
       [ 91.4],
       [ 81.8],
       [ 96.8],
       [ 69.1],
       [ 82.7],
       [ 75.5],
       [ 79.5],
       [ 73.6],
       [ 91.8],
       [ 84.1],
       [ 85.9],
       [ 81.8],
       [ 82.5],
       [ 80.5],
       [ 70. ],
       [ 81.8],
       [ 84.1],
       [ 90.5],
       [ 91.4],
       [ 89.1],
       [ 85. ],
       [ 69.1],
       [ 73.6],
       [ 80.5],
       [ 82.7],
       [ 86.4],
       [ 67.7],
       [ 92.7],
       [ 93.6],
       [ 70.9],
       [ 75. ],
       [ 93.2],
       [ 93.2],
       [ 77.7],
       [ 61.4],
       [ 94.1],
       [ 75. ],
       [ 83.6],
       [ 85.5],
       [ 73.9],
       [ 66.8],
       [ 87.3],
       [ 72.3],
       [ 88.6],
       [ 75.5],
       [101.4],
       [ 91.1],
       [ 67.3],
       [ 77.7],
       [ 81.8],
       [ 75.5],
       [ 84.5],
       [ 76.6],
       [ 85. ],
       [102.5],
       [ 77.3],
       [ 71.8],
       [ 87.9],
       [ 94.3],
       [ 70.9],
       [ 64.5],
       [ 77.3],
       [ 72.3],
       [ 87.3],
       [ 80. ],
       [ 82.3],
       [ 73.6],
       [ 74.1],
       [ 85.9],
       [ 73.2],
       [ 76.3],
       [ 65.9],
       [ 90.9],
       [ 89.1],
       [ 62.3],
       [ 83.2],
       [ 83.2],
       [ 51.6],
       [ 59. ],
       [ 49.2],
       [ 63. ],
       [ 53.6],
       [ 59. ],
       [ 47.6],
       [ 69.8],
       [ 66.8],
       [ 75.2],
       [ 55.2],
       [ 54.2],
       [ 62.5],
       [ 42. ],
       [ 50. ],
       [ 49.8],
       [ 49.2],
       [ 73.2],
       [ 47.8],
       [ 68.8],
       [ 50.6],
       [ 82.5],
       [ 57.2],
       [ 87.8],
       [ 72.8],
       [ 54.5],
       [ 59.8],
       [ 67.3],
       [ 67.8],
       [ 47. ],
       [ 46.2],
       [ 55. ],
       [ 83. ],
       [ 54.4],
       [ 45.8],
       [ 53.6],
       [ 73.2],
       [ 52.1],
       [ 67.9],
       [ 56.6],
       [ 62.3],
       [ 58.5],
       [ 54.5],
       [ 50.2],
       [ 60.3],
       [ 58.3],
       [ 56.2],
       [ 50.2],
       [ 72.9],
       [ 59.8],
       [ 61. ],
       [ 69.1],
       [ 55.9],
       [ 46.5],
       [ 54.3],
       [ 54.8],
       [ 60.7],
       [ 60. ],
       [ 62. ],
       [ 60.3],
       [ 52.7],
       [ 74.3],
       [ 62. ],
       [ 73.1],
       [ 80. ],
       [ 54.7],
       [ 53.2],
       [ 75.7],
       [ 61.1],
       [ 55.7],
       [ 48.7],
       [ 52.3],
       [ 50. ],
       [ 59.3],
       [ 62.5],
       [ 55.7],
       [ 54.8],
       [ 45.9],
       [ 70.6],
       [ 67.2],
       [ 69.4],
       [ 58.2],
       [ 64.8],
       [ 71.6],
       [ 52.8],
       [ 59.8],
       [ 49. ],
       [ 50. ],
       [ 69.2],
       [ 55.9],
       [ 63.4],
       [ 58.2],
       [ 58.6],
       [ 45.7],
       [ 52.2],
       [ 48.6],
       [ 57.8],
       [ 55.6],
       [ 66.8],
       [ 59.4],
       [ 53.6],
       [ 73.2],
       [ 53.4],
       [ 69. ],
       [ 58.4],
       [ 56.2],
       [ 70.6],
       [ 59.8],
       [ 72. ],
       [ 65.2],
       [ 56.6],
       [105.2],
       [ 51.8],
       [ 63.4],
       [ 59. ],
       [ 47.6],
       [ 63. ],
       [ 55.2],
       [ 45. ],
       [ 54. ],
       [ 50.2],
       [ 60.2],
       [ 44.8],
       [ 58.8],
       [ 56.4],
       [ 62. ],
       [ 49.2],
       [ 67.2],
       [ 53.8],
       [ 54.4],
       [ 58. ],
       [ 59.8],
       [ 54.8],
       [ 43.2]])

In [ ]:
def compute_Rsquared_and_MSE(data, beta, X, Y): 

  #first we shall compute y_bar 
  y_bar = 0.
  n = len(data)
  for i in range(n): #access each row from the data set 
    y_i= float(data.iat[i,0]) #access element at mpg column
    y_bar += y_i

  y_bar /= n
  #print('y_bar',y_bar)


  #Next we shall compute sigma_yy, which is the variance of y 
  sigma_yy = 0
  for i in range(n): #access each row from the data set 
    y_i = float(data.iat[i,0]) #access element at mpg column
    sigma_yy += (y_i-y_bar)**2

  #print('sigma_yy:', sigma_yy)

  #print('\n_________________________\n')

  #now we can compute sum of squared residuals 
  sum_sq_residuals = 0.
  for i in range(n): #access each row from the data set 
    x_i = X[i,:] #access i-th row of X
    y_i = Y[i] #access i-th row of y

    y_pred_i = np.dot(x_i,beta) #compute the prediction obtained using the regression coefficients 
    e_i = y_i - y_pred_i #compute the difference between the actual observation y_i and prediction y_pred_i

    sum_sq_residuals += (e_i)**2

    
  #Then we will compute the R^2 quantity and MSE
  R_sq = 1-sum_sq_residuals/sigma_yy
  MSE = sum_sq_residuals/n
  print('R^2 :',R_sq, ' MSE:',MSE)
  
  return R_sq, MSE

In [ ]:

import scipy
from scipy import linalg
seed = 2000
auto_mpg_train_initial = drug_vs_Body_measurements.sample(frac=0.8,random_state=seed)
auto_mpg_test =drug_vs_Body_measurements.drop(auto_mpg_train_initial.index)


seeds = [100, 200,300,400,500]

lambdas = [0.00001,0.0001, 0.001, 0.01, 0.1, 1,10,100,1000,10000]

train_R2_seeds = [] 







val_R2_seeds = [] 

train_MSE_seeds = [] 
val_MSE_seeds = [] 
cols = [1,2,3,4,5,6,7]
response_cols = [0]

for seed in seeds: 
  auto_mpg_train = auto_mpg_train_initial.sample(frac=0.8,random_state=seed)
  auto_mpg_val = auto_mpg_train_initial.drop(auto_mpg_train.index)

  X_train = auto_mpg_train[auto_mpg_train.columns[cols]]
  X_val = auto_mpg_val[auto_mpg_val.columns[cols]]
  

  X_train = X_train.to_numpy()
  X_val = X_val.to_numpy()

  X_train = np.hstack((X_train, np.ones((X_train.shape[0], 1), dtype=X_train.dtype)))
  X_val = np.hstack((X_val, np.ones((X_val.shape[0], 1), dtype=X_val.dtype)))
  
  Y_train = auto_mpg_train[auto_mpg_train.columns[response_cols]].to_numpy()
  Y_val = auto_mpg_val[auto_mpg_val.columns[response_cols]].to_numpy()

  train_R2_lambdas = []
  val_R2_lambdas = []

  train_MSE_lambdas = []
  val_MSE_lambdas = []
  
  for lambda_ in lambdas:
    XTX = np.matmul(np.transpose(X_train),X_train)
    Xy = np.matmul(np.transpose(X_train),Y_train)
    I = np.identity(X_train.shape[1])

    beta =scipy.linalg.solve( XTX+lambda_*I,Xy)
    # print('lambda:',lambda_)
    # print('beta:',beta)
    print('***************')
    # plt.scatter(y_t2_data, e_t2_i_residuals_list,color='g')

    train_R2, train_MSE = compute_Rsquared_and_MSE(auto_mpg_train, beta, X_train, Y_train)
    train_R2_lambdas.append(train_R2)
    train_MSE_lambdas.append(train_MSE)

    val_R2, val_MSE = compute_Rsquared_and_MSE(auto_mpg_val, beta, X_val, Y_val)
    val_R2_lambdas.append(val_R2)
    val_MSE_lambdas.append(val_MSE)

  train_R2_seeds.append(np.array(train_R2_lambdas))
  train_MSE_seeds.append(np.array(train_MSE_lambdas))

  val_R2_seeds.append(np.array(val_R2_lambdas))
  val_MSE_seeds.append(np.array(val_MSE_lambdas))
 

val_R2_seeds = np.array(val_R2_seeds).squeeze()
# print(val_R2_seeds)

mean_val_R2_lambdas = np.mean(val_R2_seeds,axis=0)

train_R2_seeds = np.array(train_R2_seeds).squeeze()
# print(train_R2_seeds)

mean_train_R2_lambdas = np.mean(train_R2_seeds,axis=0)

#print('k-fold train R2 values:', train_R2_seeds)

#print('k-fold train MSEs:', train_MSE_seeds)

# print('k-fold val R2 values:', mean_val_R2_lambdas.squeeze())
# print('k-fold train R2 values:', mean_train_R2_lambdas.squeeze())

#print('k-fold val MSEs:', val_MSE_seeds)


best_lambda_idx = np.argmax(mean_val_R2_lambdas)
best_lambda = lambdas[best_lambda_idx]

print('best lambda:', best_lambda)


X_train = auto_mpg_train_initial[auto_mpg_train_initial.columns[cols]]
X_train = X_train.to_numpy()

X_train = np.hstack((X_train, np.ones((X_train.shape[0], 1), dtype=X_train.dtype)))
Y_train = auto_mpg_train_initial[auto_mpg_train_initial.columns[response_cols]].to_numpy()

X_test = auto_mpg_test[auto_mpg_test.columns[cols]]
X_test = X_test.to_numpy()
X_test = np.hstack((X_test, np.ones((X_test.shape[0], 1), dtype=X_test.dtype)))
Y_test = auto_mpg_test[auto_mpg_test.columns[response_cols]].to_numpy()


XTX = np.matmul(np.transpose(X_train),X_train)
Xy = np.matmul(np.transpose(X_train),Y_train)
I = np.identity(X_train.shape[1])

beta =scipy.linalg.solve( XTX+best_lambda*I,Xy)
print('lambda:',best_lambda)
print('Final beta:',beta)
print('***************')


# train_R2, train_MSE = compute_Rsquared_and_MSE(auto_mpg_train_initial, beta, X_train, Y_train)

# test_R2, test_MSE = compute_Rsquared_and_MSE(auto_mpg_test, beta, X_test, Y_test)

# print('T1_R^2 :', train_R2, ' T1 MSE:', train_MSE)
# print('T2_R^2 :', test_R2, ' T2 MSE:', test_MSE)

***************
R^2 : [0.62813247]  MSE: [3.36193255]
R^2 : [0.73709668]  MSE: [1.94855745]
***************
R^2 : [0.62813247]  MSE: [3.36193256]
R^2 : [0.73709814]  MSE: [1.94854659]
***************
R^2 : [0.62813242]  MSE: [3.36193298]
R^2 : [0.73711271]  MSE: [1.94843865]
***************
R^2 : [0.62812784]  MSE: [3.36197439]
R^2 : [0.7372506]  MSE: [1.94741661]
***************
R^2 : [0.62775035]  MSE: [3.36538718]
R^2 : [0.73798993]  MSE: [1.94193696]
***************
R^2 : [0.61768539]  MSE: [3.45638117]
R^2 : [0.72921326]  MSE: [2.00698685]
***************
R^2 : [0.59668743]  MSE: [3.64621683]
R^2 : [0.70476416]  MSE: [2.18819601]
***************
R^2 : [0.58873575]  MSE: [3.71810533]
R^2 : [0.70543187]  MSE: [2.18324715]
***************
R^2 : [0.56372248]  MSE: [3.9442421]
R^2 : [0.69729693]  MSE: [2.24354076]
***************
R^2 : [0.51001624]  MSE: [4.42978263]
R^2 : [0.6167664]  MSE: [2.84040791]
***************
R^2 : [0.64591686]  MSE: [2.94908881]
R^2 : [0.64933367]  MSE: [3.58987852]
***************
R^2 : [0.64591686]  MSE: [2.94908881]
R^2 : [0.64933711]  MSE: [3.58984332]
***************
R^2 : [0.64591681]  MSE: [2.94908927]
R^2 : [0.64937141]  MSE: [3.58949218]
***************
R^2 : [0.64591139]  MSE: [2.9491344]
R^2 : [0.64970682]  MSE: [3.58605846]
***************
R^2 : [0.64546164]  MSE: [2.95288027]
R^2 : [0.65241144]  MSE: [3.55837052]
***************
R^2 : [0.63304801]  MSE: [3.05627096]
R^2 : [0.65723589]  MSE: [3.50898107]
***************
R^2 : [0.60602621]  MSE: [3.2813302]
R^2 : [0.64924649]  MSE: [3.590771]
***************
R^2 : [0.59698713]  MSE: [3.35661497]
R^2 : [0.646824]  MSE: [3.61557081]
***************
R^2 : [0.57226994]  MSE: [3.56247959]
R^2 : [0.63597114]  MSE: [3.72667485]
***************
R^2 : [0.51106784]  MSE: [4.07221981]
R^2 : [0.58157027]  MSE: [4.28359326]
***************
R^2 : [0.65179201]  MSE: [3.09036068]
R^2 : [0.61406577]  MSE: [3.07401019]
***************
R^2 : [0.65179201]  MSE: [3.09036068]
R^2 : [0.61406352]  MSE: [3.07402806]
***************
R^2 : [0.65179197]  MSE: [3.09036104]
R^2 : [0.61404107]  MSE: [3.07420694]
***************
R^2 : [0.65178804]  MSE: [3.09039588]
R^2 : [0.61381397]  MSE: [3.07601578]
***************
R^2 : [0.65146552]  MSE: [3.09325828]
R^2 : [0.61136389]  MSE: [3.09553093]
***************
R^2 : [0.64300017]  MSE: [3.16838864]
R^2 : [0.58987766]  MSE: [3.26667124]
***************
R^2 : [0.62566818]  MSE: [3.32221081]
R^2 : [0.55613976]  MSE: [3.53539746]
***************
R^2 : [0.61909018]  MSE: [3.38059081]
R^2 : [0.53909914]  MSE: [3.67112792]
***************
R^2 : [0.60260752]  MSE: [3.52687514]
R^2 : [0.49063292]  MSE: [4.05716687]
***************
R^2 : [0.55243809]  MSE: [3.97213098]
R^2 : [0.4062304]  MSE: [4.7294426]
***************
R^2 : [0.66431256]  MSE: [3.06304488]
R^2 : [0.51883156]  MSE: [3.36206258]
***************
R^2 : [0.66431256]  MSE: [3.06304488]
R^2 : [0.51882283]  MSE: [3.36212361]
***************
R^2 : [0.66431254]  MSE: [3.06304513]
R^2 : [0.51873555]  MSE: [3.36273344]
***************
R^2 : [0.66430987]  MSE: [3.06306951]
R^2 : [0.51786875]  MSE: [3.36879002]
***************
R^2 : [0.66408866]  MSE: [3.06508791]
R^2 : [0.50977069]  MSE: [3.4253735]
***************
R^2 : [0.65806006]  MSE: [3.12009704]
R^2 : [0.46391971]  MSE: [3.74574754]
***************
R^2 : [0.6450145]  MSE: [3.23913381]
R^2 : [0.41646375]  MSE: [4.07733597]
***************
R^2 : [0.63790503]  MSE: [3.3040055]
R^2 : [0.42566284]  MSE: [4.01305931]
***************
R^2 : [0.61811447]  MSE: [3.48458835]
R^2 : [0.40552802]  MSE: [4.15374704]
***************
R^2 : [0.56627511]  MSE: [3.95760662]
R^2 : [0.33467754]  MSE: [4.64879978]
***************
R^2 : [0.65070133]  MSE: [3.05417711]
R^2 : [0.63084351]  MSE: [3.16917882]
***************
R^2 : [0.65070133]  MSE: [3.05417712]
R^2 : [0.63084284]  MSE: [3.16918459]
***************
R^2 : [0.65070129]  MSE: [3.05417748]
R^2 : [0.63083609]  MSE: [3.16924251]
***************
R^2 : [0.65069717]  MSE: [3.05421354]
R^2 : [0.63076563]  MSE: [3.16984739]
***************
R^2 : [0.65035475]  MSE: [3.05720757]
R^2 : [0.62982447]  MSE: [3.17792714]
***************
R^2 : [0.6408791]  MSE: [3.14006017]
R^2 : [0.61749568]  MSE: [3.28376886]
***************
R^2 : [0.62011018]  MSE: [3.32165829]
R^2 : [0.59523365]  MSE: [3.47488661]
***************
R^2 : [0.61195025]  MSE: [3.39300656]
R^2 : [0.59296395]  MSE: [3.49437183]
***************
R^2 : [0.58873706]  MSE: [3.59597665]
R^2 : [0.57880543]  MSE: [3.61592158]
***************
R^2 : [0.53203344]  MSE: [4.09177846]
R^2 : [0.51676674]  MSE: [4.14851871]
best lambda: 1e-05
lambda: 1e-05
Final beta: [[ 0.01523748]
 [ 0.11025581]
 [ 0.45791563]
 [ 0.38589566]
 [-0.04108446]
 [ 0.15791506]
 [ 0.12158106]
 [10.0697141 ]]
***************